Pruebas.Cliente/Controllers/PersonalController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Pruebas.Cliente.Interface;

namespace Pruebas.Cliente.Controllers
{
    public class PersonalController : Controller
    {
        private readonly IPersonal? _personal;

        public PersonalController(IPersonal personal)
        {
            _personal = personal;
        }

        public IActionResult PersonalIndex()
        {
            var lstPersonal = _personal.ObtenerPersonal(string.Empty);

            return View(lstPersonal);
        }

        public IActionResult PersonalIndexJson()
        {
            var lstPersonal = _personal.ObtenerPersonal(string.Empty);

            return View(lstPersonal);
        }
        //
        [HttpGet]
        public JsonResult ObtenerPersonalJson()
        {
            //
            string status = "OK";
            List<Models.Personal> _lstPersonal = new List<Models.Personal>();
            //
            try
            {
                //
                _lstPersonal = _personal.ObtenerPersonal(string.Empty);
            }
            catch (Exception ex)
            {
                //
                status = String.Format("PERSONAL | ERROR | {0}-{1}", ex.Message, ex.StackTrace);
                //
                throw;
            }

            //
            var json = Json(_lstPersonal);

            //json.MaxJsonLength = int.MaxValue;
            //
            return json;
        }
        //
        // GET: HomeController1/Delete/5
        [HttpGet]
        public JsonResult Delete(int id)
        {
            //  
            string status = "OK";
            //
            try
            {
                //
                status = _personal.BorrarPersonal(id).ToString();
            }
            catch (Exception ex)
            {
                //
                status = String.Format("PERSONAL | ERROR | {0}-{1}", ex.Message, ex.StackTrace);
                //
                throw;
            }
            //
            var json = Json(status);
            //
            return json;
        }
        //
        [HttpGet]

        public JsonResult DeleteJson(int id)
        {
            //  
            string status = "OK";
            //
            try
            {
                //
                status = _personal.BorrarPersonal(id).ToString();
            }
            catch (Exception ex)
            {
                //
                status = String.Format("PERSONAL | ERROR | {0}-{1}", ex.Message, ex.StackTrace);
                //
                throw;
            }

            var lstPersonal = _personal.ObtenerPersonal(string.Empty);

            var json = Json(lstPersonal);

            return json;
        }



        //
        /*
            // GET: HomeController1
            public ActionResult Index()
            {
                return View();
            }

            // GET: HomeController1/Details/5
            public ActionResult Details(int id)
            {
                return View();
            }

            // GET: HomeController1/Create
            public ActionResult Create()
            {
                return View();
            }

            // POST: HomeController1/Create
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create(IFormCollection collection)
            {
                try
                {
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }

            // GET: HomeController1/Edit/5
            public ActionResult Edit(int id)
            {
                return View();
            }

            // POST: HomeController1/Edit/5
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit(int id, IFormCollection collection)
            {
                try
                {
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }



            // POST: HomeController1/Delete/5
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Delete(int id, IFormCollection collection)
            {
                try
                {
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
          */
    }
}

Pruebas.Cliente/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Pruebas.Cliente.Interface;
using Pruebas.Cliente.Models;

namespace Pruebas.Cliente.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProducto _producto;

        public ProductoController(IProducto producto)
        {
            _producto = producto;
        }
       
        public IActionResult ProductoIndex()
        {            
            var lstProducto = _producto.ObtenerProductos(string.Empty);

            return View(lstProducto);
        }

        //public IActionResult EditarProductos(int id)
        //{
        //    var producto = _producto.ObtenerProductos(id);

        //    ViewBag.IdProducto = id;

        //    return View(producto);
        //}

        [HttpPost]

        public IActionResult EditarProductos(TblProducto Producto, int IdProducto)
        {
            try
            {
                var pro = _producto.ActualizarProducto(Producto);

                return View(pro);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult AgregarProducto()
        {
            TblProducto producto = new TblProducto();

            return View(producto);
        }

        [HttpPost]
        public IActionResult AgregarProducto(TblProducto producto)
        {
            _producto.AgregarProducto(producto);

            return View(producto);
        }

        //public IActionResult EliminarProducto(int id)
        //{
        //    var producto = _producto.ObtenerProducto(id);

        //    ViewBag.IdProducto = id;

        //    return View(producto);
        //}

        public IActionResult EliminarsProductoConfirm(int idProducto)
        {
            var producto = _producto.EliminarProducto(idProducto);

            return Json(producto);
        }
    }
}

Pruebas.Cliente/Controllers/UsuarioController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Wordprocessing;
using Irony.Parsing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query;
using Pruebas.Cliente.Interface;
using Pruebas.Cliente.Models;
using Pruebas.Cliente.Utilidades;

namespace Pruebas.Cliente.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuario _usuario;

        public UsuarioController(IUsuario usuario)
        {
            _usuario = usuario;
        }

        public async Task<IActionResult> Index(string? nombreUsuario, int pageNumber)
        {
            int pageSize = 5;

            ViewBag.Busqueda = nombreUsuario;

            if (string.IsNullOrEmpty(nombreUsuario))
            {
                nombreUsuario = string.Empty;
            }

            if(pageNumber == 0)
            {
                pageNumber = 1;
            }
            
            var response = new ResponseViewModel<TblUsuario>();

            try
            {
                if (string.IsNullOrEmpty(nombreUsuario))
                {
                    nombreUsuario = string.Empty;
                }

                var lstUsuario = await _usuario.ObtenerUsuarios(nombreUsuario, pageNumber, pageSize);
                
                response.DataList = lstUsuario;
                response.Message = "Usuarios encontrados";

                return View(response);                
            }
            catch (Exception ex)
            {                
                var tblUsuario = new ResponseViewModel<TblUsuario>
                {
                    DataList = new PaginatedList<TblUsuario?>(),
                    Error = new Utilidades.ErrorViewModel
                    {
                        Code = "ERROR_CODE",
                        Message = $"Error al obtener la lista de usuarios: {ex.Message}"
                    }
                };
                return View(tblUsuario);
            }
        }

        public IActionResult EditarUsuario(int id)
        {
            var response = new ResponseViewModel<TblUsuario>();

            response.Error = new Utilidades.ErrorViewModel();

            var usuario = _usuario.ObtenerUsuarios(id);

            response.Data = usuario;

            ViewBag.IdUsuario = id;

            return View(response);
        }

        [HttpPost]

        public IActionResult EditarUsuario(TblUsuario usuario, int IdUsuario)
        {
            var response = new ResponseViewModel<TblUsuario>();

            try
            {
                var usr = _usuario.ActualizarUsuarios(usuario);

                response.Data = usr;
                response.Message = "Se actualizo el usuario";

                return View(response);
            }
            catch (Exception ex)
            {
                var tblUsuario = new ResponseViewModel<TblUsuario>
                {
                    Data = new TblUsuario(),
                    Error = new Utilidades.ErrorViewModel
                    {
                        Code = "ERROR_CODE",
                        Message = $"Error al actualizar el usuario: {ex.Message}"
                    }
                };

                return View(tblUsuario);
            }
        }

        public IActionResult AgregarUsuario()
        {
            TblUsuario usuario = new TblUsuario();

            return View(usuario);
        }

        [HttpPost]
        public IActionResult AgregarUsuario(TblUsuario usuario)
        {
            _usuario.AgregarUsuario(usuario);

            return View(usuario);
        }

        public IActionResult EliminarUsuario(int id)
        {
            var usuario = _usuario.ObtenerUsuarios(id);

            ViewBag.IdUsuario = id;

            return View(usuario);
        }

        public IActionResult EliminarUsuarioConfirm(int idUsuario)
        {
            try
            {
                var response = new ResponseViewModel<TblUsuario>();

                var usuario = _usuario.EliminarUsuarios(idUsuario);

                response.Success = true;
                response.Message = "Se elimino el usuario";

                return Json(response);
            }
            catch (Exception ex)
            {
                var tblUsuario = new ResponseViewModel<TblUsuario>
                {
                    Data = new TblUsuario(),
                    Success = false,
                    Error = new Utilidades.ErrorViewModel
                    {
                        Code = "ERROR_CODE",
                        Message = $"Error al eliminar el usuario: {ex.Message}"
                    }
                };
                return Json(tblUsuario);
            }
        }

        //[HttpPost]
        public async Task<IActionResult> ExportarExcel(string? nombreUsuario)
        {            
            string excelName = $"Usuarios-{DateTime.Now:yyyyMMddHHmmss}.xlsx";

            if (string.IsNullOrEmpty(nombreUsuario))
            {
                nombreUsuario = string.Empty;
            }

            try
            {                
                var lstUsuario = await _usuario.ObtenerUsuariosToList(nombreUsuario);             

                using (var workbook = new XLWorkbook())
                {
                    var worksheet = workbook.Worksheets.Add("Usuarios");

                    // Añadir el encabezado
                    worksheet.Cell(1, 1).Value = "ID";
                    worksheet.Cell(1, 2).Value = "Nombre";
                    worksheet.Cell(1, 3).Value = "Apellido Paterno";
                    worksheet.Cell(1, 4).Value = "Apellido Materno";
                    worksheet.Cell(1, 5).Value = "Identificacion";
                    worksheet.Cell(1, 6).Value = "Cargo";
                    worksheet.Cell(1, 7).Value = "Activo";
                    worksheet.Cell(1, 8).Value = "Fecha Creacion";

                    int row = 2;
                    // Añadir los datos                    
                    foreach (var usuario in lstUsuario)
                    {
                        worksheet.Cell(row, 1).Value = usuario.IdUsuario;
                        worksheet.Cell(row, 2).Value = usuario.Nombre;
                        worksheet.Cell(row, 3).Value = usuario.ApellidoPaterno;
                        worksheet.Cell(row, 4).Value = usuario.ApellidoMaterno;
                        worksheet.Cell(row, 5).Value = usuario.Identificacion;
                        worksheet.Cell(row, 6).Value = usuario.Cargo;
                        worksheet.Cell(row, 7).Value = (XLCellValue)usuario.Activo;
                        worksheet.Cell(row, 8).Value = usuario.FechaCreacion.ToString();

                        row++;
                    }

                    using (var stream = new MemoryStream())
                    {
                        workbook.SaveAs(stream);
                        var content = stream.ToArray();
                        return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public async Task<IActionResult> ImportarExcel(IFormFile fileInput)
        {
            try
            {
                if (fileInput == null || fileInput.Length == 0)
                {
                    return BadRequest("No se ha proporcionado un archivo.");
                }

                var response = new ResponseViewModel<TblUsuario>();

                var usuarios = new List<TblUsuario>();

                using (var stream = new MemoryStream())
                {
                    await fileInput.CopyToAsync(stream);
                    using (var workbook = new XLWorkbook(stream))
                    {
                        var worksheet = workbook.Worksheet(1);
                        var rows = worksheet.RowsUsed();

                        var firstRowUsed = worksheet.FirstRowUsed();
                        // Obtener el número de la primera fila utilizada
                        int firstRowNumber = firstRowUsed.RowNumber();

                        foreach (var row in rows)
                        {
                            if (row.RowNumber() == firstRowNumber)
                            {
                                // Omitir la primera fila (encabezado)
                                continue;
                            }

                            var usuario = new TblUsuario();                            

                            //usuario.IdUsuario = row.Cell(1).GetValue<int>();
                            usuario.Nombre = row.Cell(2).GetString();
                            usuario.ApellidoPaterno = row.Cell(3).GetString();
                            usuario.ApellidoMaterno = row.Cell(4).GetString();
                            usuario.Identificacion = row.Cell(5).GetValue<int>();
                            usuario.Cargo = row.Cell(6).GetString();
                            usuario.Activo = row.Cell(7).GetValue<bool>();

                            string fecha = row.Cell(8).GetString();
                            usuario.FechaCreacion = Convert.ToDateTime(fecha);

                            usuarios.Add(usuario);
                        }
                    }
                }    
                // Guardar los productos en la base de datos
                _usuario.AgregarUsuarios(usuarios);
                
                var lstUsuario = await _usuario.ObtenerUsuarios(string.Empty, 1, 5);
                response.DataList = lstUsuario;
                response.Message = "Usuarios encontrados";
                
                return PartialView("UsuariosPartialView", response);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Pruebas.Cliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>::[SIGA-FFMM]::</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <link href="~/css/Datepicker/jquery-ui.css" rel="stylesheet" />
    <script src="~/js/Datepicker/jquery-3.7.1.js"></script>
    <script src="~/js/Datepicker/jquery-ui.js"></script>

    <!-- INICIO CDN / STYLES -->
    <link type="text/css"
          rel="stylesheet"
          href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" />
    <link type="text/css"
          rel="stylesheet"
          href="https://code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css" />
    <link type="text/css"
          rel="stylesheet"
          href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link type="text/css"
          rel="stylesheet"
          href="https://cdn.datatables.net/v/ju/dt-1.12.1/r-2.3.0/datatables.min.css" />
    <!-- FIN  CDN / STYLES -->
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="/">[SIGMA-FFMM]</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!--<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>-->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">

                        @*   <div class="sb-sidenav-menu-heading">Login</div>
                        <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Login">Login</a> *@

                        <!--
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseUsr" aria-expanded="false" aria-controls="collapseUsr">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Usuarios
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>


                        <div class="collapse" id="collapseUsr" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="Index">Lista Usuarios</a>
                        @*  <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="AgregarUsuario">Agregar Usuarios</a>
                                <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="EditarUsuario">Actualizar Usuarios</a>
                                <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="EliminarUsuario">Eliminar Usuarios</a> *@
                            </nav>
                        </div>
                         -->
                        <!--
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseProd" aria-expanded="false" aria-controls="collapseProd">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Productos
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseProd" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="ProductoIndex">Lista Productos</a>
                                <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="AgregarProducto">Agregar Producto</a>
                                <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="ActualizarProducto">Actualizar Producto</a>
                                <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="EliminarProducto">Eliminar Producto</a>
                            </nav>
                        </div>
                        --->

                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseProveedor" aria-expanded="false" aria-controls="collapseProveedor">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Personal
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseProveedor" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="" asp-controller="Personal" asp-action="PersonalIndexJson">Listado de Personal</a>
                                <!--
                                <a class="nav-link" asp-area="" asp-controller="Proveedor" asp-action="AgregarProveedor">Agregar Proveedor</a>
                                <a class="nav-link" asp-area="" asp-controller="Proveedor" asp-action="ActualizarProveedor">Actualizar Proveedor</a>
                                <a class="nav-link" asp-area="" asp-controller="Proveedor" asp-action="EliminarProveedor">Eliminar Proveedor</a>
                                -->
                            </nav>
                        </div>
                        @*  <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseProveedor" aria-expanded="false" aria-controls="collapseProveedor">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Proveedores
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseProveedor" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" asp-area="" asp-controller="Proveedor" asp-action="Index">Lista Proveedor</a>
                        <a class="nav-link" asp-area="" asp-controller="Proveedor" asp-action="AgregarProveedor">Agregar Proveedor</a>
                        <a class="nav-link" asp-area="" asp-controller="Proveedor" asp-action="ActualizarProveedor">Actualizar Proveedor</a>
                        <a class="nav-link" asp-area="" asp-controller="Proveedor" asp-action="EliminarProveedor">Eliminar Proveedor</a>
                        </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseVenta" aria-expanded="false" aria-controls="collapseVenta">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Venta
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseVenta" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" asp-area="" asp-controller="Venta" asp-action="Index">Registrar Venta</a>
                        <a class="nav-link" asp-area="" asp-controller="Venta" asp-action="BuscarVenta">Buscar Venta</a>
                        </nav>
                        </div> *@
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer style="background-color:black; color:aqua">
                <hr>
                <div align="center">
                    <h6>Aplicacion SIGA-FFMM Version [1.0.15]</h6>
                </div>
                <hr>
            </footer>

            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @await RenderSectionAsync("Scripts", required: false)
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
            <script src="~/js/scripts.js"></script>

            <!-- INICIO CDN / SCRIPT  -->
            <script type="text/javascript"
                    src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
            <script type="text/javascript"
                    src="https://cdn.datatables.net/v/ju/dt-1.12.1/r-2.3.0/datatables.min.js"></script>
            <!-- FIN CDN / SCRIPT -->

        </div>
    </div>
</body>
</html>